const GET_QUESTIONS = 'GET_QUESTIONS';
const ANSWER_QUESTION = 'ANSWER_QUESTION';
const GET_FINAL_SCORE = 'GET_FINAL_SCORE';




export const ActionTypes = {
    GET_QUESTIONS,
    ANSWER_QUESTION,
    GET_FINAL_SCORE,
};

